# Generated by Django 2.2.28 on 2023-04-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='product',
            new_name='category',
        ),
    ]
