# Generated by Django 2.2.28 on 2023-04-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20230426_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=models.ManyToManyField(to='Product.Ingredient'),
        ),
        migrations.DeleteModel(
            name='ProductsIngredients',
        ),
    ]
